export const WEATHER_ICONS = {
	"113": { "daycondition": "Sunny", "text": "Sunny", "iconUrl": "/weatherIcons/sunny.png", "emoji": "☀️" },
	"116": { "daycondition": "Partly cloudy", "text": "Partly Cloudy", "iconUrl": "/weatherIcons/cloudy.png", "emoji": "⛅️" },
	"119": { "daycondition": "Cloudy", "text": "Cloudy", "iconUrl": "/weatherIcons/cloudy.png", "emoji": "☁️" },
	"122": { "daycondition": "Overcast", "text": "Very Cloudy", "iconUrl": "/weatherIcons/cloudy.png", "emoji": "☁️" },
	"143": { "daycondition": "Mist", "text": "Fog", "iconUrl": "/weatherIcons/cloudy.png", "emoji": "🌫" },
	"176": { "daycondition": "Patchy rain possible", "text": "Light Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌦" },
	"179": { "daycondition": "Patchy snow possible", "text": "Light Sleet Showers", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌧" },
	"182": { "daycondition": "Patchy sleet possible", "text": "Light Sleet", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌧" },
	"185": { "daycondition": "Patchy freezing drizzle possible", "text": "Light Sleet", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌧" },
	"200": { "daycondition": "Thundery outbreaks possible", "text": "Thundery Showers", "iconUrl": "/weatherIcons/storm.png", "emoji": "⛈" },
	"227": { "daycondition": "Blowing snow", "text": "Light Snow", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌨" },
	"230": { "daycondition": "Blizzard", "text": "Heavy Snow", "iconUrl": "/weatherIcons/snowy.png", "emoji": "❄️" },
	"248": { "daycondition": "Fog", "text": "Fog", "iconUrl": "/weatherIcons/cloudy.png", "emoji": "🌫" },
	"260": { "daycondition": "Freezing fog", "text": "Fog", "iconUrl": "/weatherIcons/cloudy.png", "emoji": "🌫" },
	"263": { "daycondition": "Patchy light drizzle", "text": "Light Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌦" },
	"266": { "daycondition": "Light drizzle", "text": "Light Rain", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌦" },
	"281": { "daycondition": "Freezing drizzle", "text": "Light Sleet", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"284": { "daycondition": "Heavy freezing drizzle", "text": "Light Sleet", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"293": { "daycondition": "Patchy light rain", "text": "Light Rain", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌦" },
	"296": { "daycondition": "Light rain", "text": "Light Rain", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌦" },
	"299": { "daycondition": "Moderate rain at times", "text": "Heavy Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"302": { "daycondition": "Moderate rain", "text": "Heavy Rain", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"305": { "daycondition": "Heavy rain at times", "text": "Heavy Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"308": { "daycondition": "Heavy rain", "text": "Heavy Rain", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"311": { "daycondition": "Light freezing rain", "text": "Light Sleet", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"314": { "daycondition": "Light Sleet", "text": "Light Sleet", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"317": { "daycondition": "Light Sleet", "text": "Light Sleet", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"320": { "daycondition": "Light Snow", "text": "Light Snow", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌨" },
	"323": { "daycondition": "Light Snow Showers", "text": "Light Snow Showers", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌨" },
	"326": { "daycondition": "Light Snow Showers", "text": "Light Snow Showers", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌨" },
	"329": { "daycondition": "Heavy Snow", "text": "Heavy Snow", "iconUrl": "/weatherIcons/snowy.png", "emoji": "❄️" },
	"332": { "daycondition": "Heavy Snow", "text": "Heavy Snow", "iconUrl": "/weatherIcons/snowy.png", "emoji": "❄️" },
	"335": { "daycondition": "Heavy Snow Showers", "text": "Heavy Snow Showers", "iconUrl": "/weatherIcons/snowy.png", "emoji": "❄️" },
	"338": { "daycondition": "Heavy Snow", "text": "Heavy Snow", "iconUrl": "/weatherIcons/snowy.png", "emoji": "❄️" },
	"350": { "daycondition": "Light Sleet", "text": "Light Sleet", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"353": { "daycondition": "Light Showers", "text": "Light Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌦" },
	"356": { "daycondition": "Heavy Showers", "text": "Heavy Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"359": { "daycondition": "Heavy Rain", "text": "Heavy Rain", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"362": { "daycondition": "Light Sleet Showers", "text": "Light Sleet Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"365": { "daycondition": "Light Sleet Showers", "text": "Light Sleet Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"368": { "daycondition": "Light Snow Showers", "text": "Light Snow Showers", "iconUrl": "/weatherIcons/snowy.png", "emoji": "🌨" },
	"371": { "daycondition": "Heavy Snow Showers", "text": "Heavy Snow Showers", "iconUrl": "/weatherIcons/snowy.png", "emoji": "❄️" },
	"374": { "daycondition": "Light Sleet Showers", "text": "Light Sleet Showers", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"377": { "daycondition": "Light Sleet", "text": "Light Sleet", "iconUrl": "/weatherIcons/rainy.png", "emoji": "🌧" },
	"386": { "daycondition": "Thundery Showers", "text": "Thundery Showers", "iconUrl": "/weatherIcons/storm.png", "emoji": "⛈" },
	"389": { "daycondition": "Thundery Heavy Rain", "text": "Thundery Heavy Rain", "iconUrl": "/weatherIcons/storm.png", "emoji": "🌩" },
	"392": { "daycondition": "Thundery Snow Showers", "text": "Thundery Snow Showers", "iconUrl": "/weatherIcons/storm.png", "emoji": "⛈" },
	"395": { "daycondition": "Heavy Snow Showers", "text": "Heavy Snow Showers", "iconUrl": "/weatherIcons/snowy.png", "emoji": "❄️" }
}
